### ISSUE TITLE
Move `Pair` out of `Schnorr`

### ISSUE THREAD

**Issue by Geod24** [bosagora/crypto#6]
The `Pair` type binds together a `Scalar` and its `Point`.
It currently lives in `Schnorr`, however it should probably be put somewhere else (`ECC` ? `Types` ?) as the idea is that `Schnorr` exposes the routines for signing, but many modules that will hold a `Pair` might not need to sign themselves, and the modules that need will need `ECC` anyway.

**Comment by kchulj** [comment]
Fixed by #21 ?

**Comment by Geod24** [comment]
Indeed.
